### ISSUE TITLE
Body.json returns object, not JSON

### ISSUE THREAD

**Issue by OliverJAsh** [ryan-codingintrigue/typescript-fetch#1]
This is incorrect: https://github.com/ryan-codingintrigue/typescript-fetch/blob/a9288b20effd3c8dcf1959faf1f2029708e4f081/src/fetch.js.d.ts#L34

It returns an object representing the JSON, not `window.JSON` itself.

**Comment by ryan-codingintrigue** [comment]
Thanks @OliverJAsh, I merged this repository into the [DefinitelyTyped repo](https://github.com/borisyankov/DefinitelyTyped), where someone has kindly submitted a pull request to fix this issue (and add some other missing stuff)
